import re

with open('src/pages/ComputerReadingTest.tsx', 'r') as f:
    content = f.read()

# First replace the bad portion with something known
bad_str = """            <div className="mt-3 text-[10px] text-gray-400 text-right italic border-t border-gray-50 p      {!reviewMode && ("""
good_str = """            <div className="mt-3 text-[10px] text-gray-400 text-right italic border-t border-gray-50 pt-2">Powered by Free Dictionary API</div>
          </div>
        )}

      </main>

      {!reviewMode && ("""

content = content.replace(bad_str, good_str)

# Clean up the extra duplicated buttons generated by mistake
bad_button_str = """                  </div>
              </div>
            </div>

            <button
                  </div>
              </div>
            </div>

            <button"""
good_button_str = """                  </div>
              </div>
            </div>

            <button"""

content = content.replace(bad_button_str, good_button_str)

with open('src/pages/ComputerReadingTest.tsx', 'w') as f:
    f.write(content)
