const fs = require('fs');

const answers = {
  "1": "v", "2": "i", "3": "vi", "4": "x", "5": "ix", "6": "iv", "7": "ii",
  "8": "TRUE", "9": "TRUE", "10": "NOT GIVEN",
  "11": "C", "12": "D", "13": "E",
  "14": "12 stripes", "15": "12 million", "16": "Australia", "17": "Europeans",
  "18": "A", "19": "D", "20": "C", "21": "B", "22": "A", "23": "D",
  "24": "B", "25": "D", "26": "A",
  "27": "YES", "28": "NO", "29": "YES", "30": "NOT GIVEN", "31": "YES", "32": "NO",
  "33": "D", "34": "A", "35": "C", "36": "A", "37": "C", "38": "A", "39": "F", "40": "B"
};

const explanations = {
  "1": { passageId: 1, highlights: ["16th and 17th centuries saw two great pioneers of modern science..."], explanation: "Paragraph A introduces Gilbert and Galileo as leading figures of early science.\n\n**Synonyms:**\n• pioneers = early science" },
  "2": { passageId: 1, highlights: ["Born in an eminent local family... went to grammar school, and then studied medicine..."], explanation: "Paragraph B covers his background, birth, education, and early life.\n\n**Synonyms:**\n• born / grammar school / studied = early years" },
  "3": { passageId: 1, highlights: ["culminated in his election to the president... appointed the personal physician to the Queen... and later knighted"], explanation: "Paragraph C lists his career achievements, status in society, and honors given to him by the Queen.\n\n**Synonyms:**\n• election / appointed / knighted = professional and social recognition" },
  "4": { passageId: 1, highlights: ["Gilbert was first interested in chemistry but later changed his focus..."], explanation: "Paragraph D explains how he initially studied chemistry but switched his attention to physics and magnetism.\n\n**Synonyms:**\n• changed his focus = change of focus" },
  "5": { passageId: 1, highlights: ["He investigated the nature of magnetism... found that metals can be magnetized..."], explanation: "Paragraph E details his specific experiments, findings, and what he learned about magnets and electricity.\n\n**Synonyms:**\n• investigated / found = discovery" },
  "6": { passageId: 1, highlights: ["He also questioned the traditional astronomical beliefs."], explanation: "Paragraph F discusses his views on space, stars, and the earth's orbit, challenging the old models.\n\n**Synonyms:**\n• astronomical beliefs = astronomy" },
  "7": { passageId: 1, highlights: ["His research method was revolutionary in that he used experiments rather than pure logic..."], explanation: "Paragraph G contrasts his experimental, observation-based approach with the pure logic used by ancient Greeks.\n\n**Synonyms:**\n• revolutionary = new; research method = scientific research method" },
  "8": { passageId: 1, highlights: ["...he is less well-known than he deserves."], explanation: "The text explicitly states that he does not have the level of fame he has earned.\n\n**Synonyms:**\n• well-known = famous; deserves = should be" },
  "9": { passageId: 1, highlights: ["He was a very successful and eminent doctor. All this culminated in... He was also appointed the personal physician to the Queen"], explanation: "The passage states he was an eminent doctor before being appointed to serve the Queen.\n\n**Synonyms:**\n• eminent = famous; appointed = employed" },
  "10": { passageId: 1, highlights: [], explanation: "The text says he changed his focus from chemistry due to the mysticism of alchemy, but there is no mention of him losing faith in medical theories." },
  "11": { passageId: 1, highlights: ["Gilbert also found that metals can be magnetized..."], explanation: "He discovered metals could be magnetized." },
  "12": { passageId: 1, highlights: ["he believed that stars are not equidistant from the earth"], explanation: "He theorized that stars were not all at the same distance.\n\n**Synonyms:**\n• not equidistant = different distances" },
  "13": { passageId: 1, highlights: ["would wobble all by itself in 24 hours."], explanation: "He believed the earth wobbled on an axis." },
  "14": { passageId: 2, highlights: ["It had 12 distinct stripes on its back..."], explanation: "The text describes the physical markings on the animal's back.\n\n**Synonyms:**\n• on its back = on its fur coat" },
  "15": { passageId: 2, highlights: ["Fossils of thylacines dating from about almost 12 million years ago..."], explanation: "The text mentions how old the earliest dug-up remains are.\n\n**Synonyms:**\n• dating from = had existed as early as" },
  "16": { passageId: 2, highlights: ["They were widespread in Australia 7,000 years ago, but have probably been extinct on the continent..."], explanation: "They were found everywhere on the mainland before dying out there.\n\n**Synonyms:**\n• widespread = lived throughout; the continent = the mainland" },
  "17": { passageId: 2, highlights: ["...declining in Tasmania at the time of European settlement 200 years ago, but the decline was certainly accelerated by the new arrivals."], explanation: "The decline of the animal sped up rapidly when foreign settlers arrived 200 years ago.\n\n**Synonyms:**\n• accelerated = shrunk at a higher speed" },
  "18": { passageId: 2, highlights: ["“I was besieged by television crews, including four to five from Japan, and others from the United Kingdom, Germany...”"], explanation: "His sighting brought massive media attention from around the globe.\n\n**Synonyms:**\n• television crews from Japan, UK, Germany = international interest" },
  "19": { passageId: 2, highlights: ["Mooney has seen it all – the mistakes, the hoaxes, the illusions..."], explanation: "He acknowledges that many people are simply mistaken or lying.\n\n**Synonyms:**\n• mistakes, hoaxes, illusions = not trusted" },
  "20": { passageId: 2, highlights: ["...despite scientific thinking that 500 animals are required to sustain a population, the Florida panther is down to a dozen..."], explanation: "He uses the Florida panther to prove that species can survive with far fewer animals than scientists claim.\n\n**Synonyms:**\n• despite scientific thinking that 500 animals are required = doesn't require a certain number" },
  "21": { passageId: 2, highlights: ["...is now convinced that his dream will go unfulfilled."], explanation: "Rose has given up hope of ever seeing one.\n\n**Synonyms:**\n• dream will go unfulfilled = no hope of finding" },
  "22": { passageId: 2, highlights: ["If there are thylacines out there, they are better off right where they are."], explanation: "He believes that if they are alive, humans should leave them alone.\n\n**Synonyms:**\n• better off right where they are = do not disturb them" },
  "23": { passageId: 2, highlights: ["“It is a blind optimism... If something crosses the road, it's not a case of 'I wonder what that was?' Rather, it is a case of 'that's a thylacine!'”"], explanation: "Mooney notes that people's desperation to see the animal clouds their judgment.\n\n**Synonyms:**\n• blind optimism = affected by people's beliefs" },
  "24": { passageId: 2, highlights: ["Government and private search parties combed the region..."], explanation: "Naarding's sighting triggered massive search efforts.\n\n**Synonyms:**\n• search parties combed the region = extensive interests to find" },
  "25": { passageId: 2, highlights: ["...was thought to have died out along with the dinosaurs... until a specimen was dragged to the surface..."], explanation: "The coelacanth is mentioned to prove that scientists can wrongly classify an animal as extinct.\n\n**Synonyms:**\n• thought to have died out... until a specimen was dragged = extinction can be mistaken" },
  "26": { passageId: 2, highlights: ["Mooney treats all reports on face value. 'I never try to embarrass people or make fools of them.'"], explanation: "Mooney doesn't outright mock people, taking their claims at face value initially.\n\n**Synonyms:**\n• treats on face value = give some credit" },
  "27": { passageId: 3, highlights: ["He predicts that by the middle of the next century, only about 600 will be left."], explanation: "The passage states only a small fraction of languages will survive by 2050.\n\n**Synonyms:**\n• middle of the next century = by 2050; about 600 = small number" },
  "28": { passageId: 3, highlights: ["In Australia, however, thanks to the efforts of Nick Evans and his colleagues, the record is much better."], explanation: "The text praises the Australian academics (like Nick Evans) for doing a great job at recording languages, contradicting the claim that it was \"too limited.\"\n\n**Synonyms:**\n• much better = opposite of too limited" },
  "29": { passageId: 3, highlights: ["But technology is not enough. You still need the linguist to do the analysis."], explanation: "While technology helps, the text states it cannot do the job alone without humans.\n\n**Synonyms:**\n• not enough = unsatisfactory in some respects" },
  "30": { passageId: 3, highlights: [], explanation: "The passage discusses Chomsky's academic view (Universal Grammar) but never mentions his \"political views\"." },
  "31": { passageId: 3, highlights: ["It requires a linguist to spend years in the field... And you need the money to support them."], explanation: "The work takes years and costs a lot of money.\n\n**Synonyms:**\n• years = long-term; need the money = financial support" },
  "32": { passageId: 3, highlights: ["To a theoretical linguist [like Chomsky], the death of a language is not necessarily a catastrophe. It is merely the loss of one more superficial variation."], explanation: "The text actually says the opposite; Chomsky sees language death as just a superficial loss, not a catastrophe.\n\n**Synonyms:**\n• not necessarily a catastrophe = opposite of too emotional" },
  "33": { passageId: 3, highlights: ["The answer is analogous to the reason why we should care about the loss of the ozone layer... It is about diversity."], explanation: "The author uses environmental issues to show that language diversity is just as important.\n\n**Synonyms:**\n• analogous to the reason why we should care = the public should be equally concerned" },
  "34": { passageId: 3, highlights: ["...complex systems of kinship terms that encode the social structure... If the language is replaced by a creole... this social knowledge is lost."], explanation: "Replacing a complex native language with a creole destroys the ability to express social structures.\n\n**Synonyms:**\n• social knowledge is lost = lose the ability to express ideas which are part of their culture" },
  "35": { passageId: 3, highlights: ["In South America and West Africa, where the rate of language loss is just as high as in Australia..."], explanation: "Both regions are experiencing a rapid extinction of languages.\n\n**Synonyms:**\n• rate of language loss is just as high = disappearing rapidly in both places" },
  "36": { passageId: 3, highlights: ["...complained that linguistics is the only discipline that is presiding over the disappearance of its own subject matter."], explanation: "Krauss is unhappy because linguists are watching their subject die without recording it.\n\n**Synonyms:**\n• presiding over the disappearance = failing to record languages before they die out" },
  "37": { passageId: 3, highlights: ["Austin and Co. are in no doubt that because languages are unique, even if they do tend to have common underlying features..."], explanation: "Linguist Peter Austin acknowledges that while every language is distinct, they still share basic, underlying grammatical or structural traits.\n\n**Synonyms:**\n• common underlying features = share certain universal characteristics" },
  "38": { passageId: 3, highlights: ["As Nick Evans says, a community who speak an endangered language may have reasons to doubt or even oppose efforts to preserve it."], explanation: "Nick Evans notes the tragic irony that sometimes the native speakers themselves will push back against preservation efforts, even when their language is dying.\n\n**Synonyms:**\n• endangered language = in danger of disappearing; oppose efforts to preserve = resist attempts to save" },
  "39": { passageId: 3, highlights: ["Plenty of students continue to be drawn to the intellectual thrill of linguistics fieldwork... The highest barrier, they agree, is that the linguistics profession's emphasis on theory gradually wears down the enthusiasm..."], explanation: "Despite the academic world being heavily dominated by theory (which acts as a barrier), a large number of students still want to do hands-on, practical field research.\n\n**Synonyms:**\n• students = young researchers; fieldwork = practical research; emphasis on theory = prevalence of theoretical linguistics" },
  "40": { passageId: 3, highlights: ["...he believes that good descriptive work requires thorough theoretical understanding and should also contribute to building new theory."], explanation: "Chomsky supports documenting specific languages (descriptive linguistics), but he argues this work must be built upon and contribute to theoretical understanding.\n\n**Synonyms:**\n• requires thorough theoretical understanding = provided that it has a strong basis in theory; descriptive work = descriptive linguistics" }
};

let code = fs.readFileSync('src/data/test16ReadingData.ts', 'utf8');
code = code.replace(/export const test16Answers\s*=\s*{};/, `export const test16Answers: Record<number, string> = ${JSON.stringify(answers, null, 2)};`);
code = code.replace(/export const test16Explanations\s*=\s*{};/, `export const test16Explanations: Record<number, any> = ${JSON.stringify(explanations, null, 2)};`);
fs.writeFileSync('src/data/test16ReadingData.ts', code);
console.log("Updated test16ReadingData.ts with answers and explanations.");

