const fs = require('fs');

const fullExplanations = {
  1: "The passage states that chicken is eaten worldwide and adapts easily to different cultural dishes.\\n\\n**Highlighted Text:** \"Chicken is the universal food of our era, crossing cultural boundaries with ease. With its mild taste and uniform texture, chicken presents a blank canvas for the national flavours of almost any cuisine.\"\\n\\n**Synonyms:**\\n• globally popular = universal food / crossing cultural boundaries\\n• different styles of cooking = national flavours of almost any cuisine",
  2: "The text mentions that the red junglefowl flies up to trees to nest (\"That's about as much flying as it can manage\"), but it never compares its flying ability to that of modern domestic chickens.",
  3: "The text confirms that the modern chicken descends from the red junglefowl as well as other closely related species.\\n\\n**Highlighted Text:** \"But the red junglefowl is not the sole ancestor of the modern chicken. Scientists have identified three closely related species that might have bred with the red junglefowl.\"\\n\\n**Synonyms:**\\n• more than one ancestor = not the sole ancestor / three closely related species",
  4: "The passage explicitly states that modern chickens got their yellow skin from the grey junglefowl.\\n\\n**Highlighted Text:** \"...recent research suggests that modern chickens inherited at least one trait, their yellow skin, from the grey junglefowl...\"\\n\\n**Synonyms:**\\n• same skin colour = inherited... their yellow skin",
  5: "The passage explains that after Rome fell, the chicken industry collapsed.\\n\\n**Highlighted Text:** \"But the chicken's status in Europe appears to have diminished with the collapse of Rome. In the period after the fall of the Roman Empire, chicken farms vanished...\"\\n\\n**Synonyms:**\\n• ended = collapse / fall\\n• consumption declined = status diminished / farms vanished",
  6: "While paragraph 7 discusses the efficiency and mechanics of \"factory farms\" (e.g., \"cogs in a system designed to convert grain into protein\"), it contains no information about people criticizing these methods.",
  7: "The passage states the exact opposite; keeping chickens is becoming more popular in the USA, and people are spending a lot of money on them.\\n\\n**Highlighted Text:** \"In the USA, exotic and heritage breeds of chicken are being sold for a considerable source of money as the fashion for keeping chickens in the backyards becomes more popular.\"\\n\\n**Synonyms:**\\n• expensive breeds = exotic and heritage breeds sold for a considerable source of money\\n• at home = in the backyards\\n• fewer people (contradiction) = becomes more popular",
  8: "The text details where chickens were first placed upon arriving in Egypt.\\n\\n**Highlighted Text:** \"Chickens arrived in Egypt in around 1750 BC, as fighting birds and additions to zoos.\"\\n\\n**Synonyms:**\\n• seen in = additions to",
  9: "The passage notes where the drawings of chickens were located.\\n\\n**Highlighted Text:** \"Drawings of the birds decorated royal tombs, which contained the treasures that the kings and queens...\"\\n\\n**Synonyms:**\\n• pictures = drawings\\n• used on = decorated",
  10: "The Egyptians invented a way to hatch eggs without relying on the hens themselves.\\n\\n**Highlighted Text:** \"Egyptians mastered the technique of artificial incubation, which freed hens to lay more eggs.\"\\n\\n**Synonyms:**\\n• method = technique\\n• didn't involve hens = artificial / freed hens",
  11: "The text outlines the strict environmental conditions needed for eggs to hatch.\\n\\n**Highlighted Text:** \"...the temperature remains at around 38 degrees Celsius. The eggs must also be turned... and the humidity must remain stable at about 55 percent...\"\\n\\n**Synonyms:**\\n• stay the same = remain stable",
  12: "The text describes the large rooms used to hatch the eggs.\\n\\n**Highlighted Text:** \"The Egyptians constructed vast complexes of large rooms, which were essentially ovens...\"\\n\\n**Synonyms:**\\n• functioned as = essentially",
  13: "The text states what the chickens were protected from when raised indoors.\\n\\n**Highlighted Text:** \"This allowed chickens to be raised indoors and be protected from cold temperatures and heavy rain as well as predators.\"\\n\\n**Synonyms:**\\n• kept inside = raised indoors\\n• safe from = protected from",
  14: "Paragraph A provides examples of situations (persona projects) where we might change our behavior to suit our needs.\\n\\n**Highlighted Text:** \"...we adopt these free-traits only when we need them, in order to meet the demands of different situations... These projects might be big (such as career ambitions) or small (like cleaning the car)...\"\\n\\n**Synonyms:**\\n• contexts = different situations\\n• act out of character = adopt free-traits\\n• examples = big (such as career ambitions) or small...",
  15: "Paragraph B compares humans to scientists who test things out to see what works and what doesn't.\\n\\n**Highlighted Text:** \"We are continually exploring and testing the world around us to discover what works and what doesn't. We do things, say things, and then we observe the reactions...\"\\n\\n**Synonyms:**\\n• Learning by trial and error = exploring and testing... what works and what doesn't / observe the reactions",
  16: "Paragraph C explicitly states the researcher's motive for choosing the workplace as the setting for their study.\\n\\n**Highlighted Text:** \"The reason for basing the research on this environment... is that... I wanted to discover what happens when people push the limits of their ability to act out of character [at work].\"\\n\\n**Synonyms:**\\n• why researchers decided to focus on = the reason for basing the research on",
  17: "Paragraph D explains how physical spaces (workplace facilities) help introverts recharge after acting extroverted.\\n\\n**Highlighted Text:** \"...introvert employees make frequent use of 'restorative resources' These are spaces designed to allow employees to read quietly or simply relax in order to recover their equilibrium...\"\\n\\n**Synonyms:**\\n• workplace facilities = restorative resources / spaces designed to allow employees to read quietly",
  18: "Paragraph E discusses how stressful it is for extroverts to suppress their naturally outgoing traits.\\n\\n**Highlighted Text:** \"...extroverts report strikingly different, and much less rewarding, experiences... outwardly confident personality types find it extremely hard-and stressful-to rein back their personalities...\"\\n\\n**Synonyms:**\\n• pressure = extremely hard and stressful\\n• restraining a outgoing nature = rein back their personalities (outwardly confident types)",
  19: "Paragraph F outlines how strict, competitive environments harm employee well-being by not allowing time for personal projects.\\n\\n**Highlighted Text:** \"For example, highly competitive environments, which place demands on employees to conform to certain types of behaviour... could eventually be detrimental to their well-being.\"\\n\\n**Synonyms:**\\n• company culture = competitive environments that place demands\\n• negative impact = detrimental to their well-being",
  20: "Paragraph G offers direct advice to company management on how to improve the workplace.\\n\\n**Highlighted Text:** \"Balsari-Palsule suggests that it would serve companies well... She also believes that management should rely less on... instead, organisations should adopt policies...\"\\n\\n**Synonyms:**\\n• recommendations for employers = suggests it would serve companies well / management should / organisations should",
  21: "In the first paragraph (Paragraph A), Professor Brian Little explains that \"free-traits\" are behaviors we selectively choose to use (meaning they aren't used constantly) to go against our biological, natural inclinations.\\n\\n**Highlighted Text:** \"According to Little, we adopt these free-traits only when we need them...\"\\n\\n**Synonyms:**\\n• not used by people all the time = only when we need them",
  22: "In the first paragraph (Paragraph A), Professor Brian Little explains that \"free-traits\" are behaviors we selectively choose to use (meaning they aren't used constantly) to go against our biological, natural inclinations.\\n\\n**Highlighted Text:** \"...adoption of what he calls 'free-traits', which allow us to behave in a manner which contrasts with our natural selves.\"\\n\\n**Synonyms:**\\n• enable people to act = allow us to behave\\n• ways which are not typical for them = in a manner which contrasts with our natural selves",
  23: "In the second stage of research, the focus shifts to demanding environments.\\n\\n**Highlighted Text:** \"...highly competitive environments... may leave little time for employees to pursue projects which are important to them on a personal level.\"\\n\\n**Synonyms:**\\n• prevent employees from completing projects = leave little time to pursue projects",
  24: "The research presents many consequences and lessons that businesses should consider.\\n\\n**Highlighted Text:** \"The implications of Little and BalsariPalsule's research are numerous and need to be taken into account by businesses.\"\\n\\n**Synonyms:**\\n• has many = are numerous",
  25: "Management is advised not to categorize people strictly using these tools.\\n\\n**Highlighted Text:** \"She also believes that management should rely less on handing out personality surveys that pigeonhole employees into introvert and extrovert categories.\"\\n\\n**Synonyms:**\\n• depend too much on = should rely less on\\n• determining personality types = pigeonhole employees into introvert and extrovert categories",
  26: "Making structural changes to reduce stress will ultimately help the business perform better.\\n\\n**Highlighted Text:** \"Furthermore, making these changes is also likely to lead to increases in productivity in the long run.\"\\n\\n**Synonyms:**\\n• boost = lead to increases in\\n• over time = in the long run",
  27: "Baron-Cohen's brain scan experiment proved that auditory triggers caused visual parts of the brain to react.\\n\\n**Highlighted Text:** \"A brain scanning experiment by Baron-Cohen in 1995 found that when synesthetes were listening to words, areas of the brain lit up that are normally only active in response to vision and colour.\"\\n\\n**Synonyms:**\\n• hearing the names of things = listening to words\\n• affects the brain in the same way that looking at things does = areas of the brain lit up that are normally only active in response to vision",
  28: "Baron-Cohen conducted an experiment showing synesthetes gave the exact same colour-to-letter answers weeks later.\\n\\n**Highlighted Text:** \"...an experiment by Simon Baron-Cohen... showed that synesthetes who, when tested, had linked particular colours or shapes to letters, gave the same answers in 92 per cent of instances when tested again a week later.\"\\n\\n**Synonyms:**\\n• consistent = gave the same answers in 92 per cent of instances\\n• written symbol = letters",
  29: "John Locke described a man whose synesthesia involved a trumpet and the colour red.\\n\\n**Highlighted Text:** \"Seventeenth-century English philosopher John Locke... wrote about a man who experienced bright red as the sound of the trumpet.\"\\n\\n**Synonyms:**\\n• musical instrument = trumpet\\n• certain colour = bright red",
  30: "Smilek points out that studying this abnormal condition helps scientists understand regular brain functions.\\n\\n**Highlighted Text:** \"'When scientists study normal perception,' says Daniel Smilek... Synesthesia, because it's abnormal, can give us new insights into normal perception.\"\\n\\n**Synonyms:**\\n• experience things differently = abnormal\\n• fresh perspectives on how the senses usually work = new insights into normal perception",
  31: "Paragraph F details the use of a brain scanner.\\n\\n**Highlighted Text:** \"A brain scanning experiment by Baron-Cohen in 1995...\"\\n\\n**Synonyms:**\\n• modern medical technology = brain scanning experiment",
  32: "Paragraph I names a famous author who had the condition.\\n\\n**Highlighted Text:** \"...explain what's going on in the brains of people like the novelist Nabokov, who perceived the English 'a' as dark brown...\"\\n\\n**Synonyms:**\\n• writer = novelist",
  33: "Paragraph A explicitly breaks down the literal translation and medical definition of the term.\\n\\n**Highlighted Text:** \"...synesthesia – meaning literally 'joined sensation' – an extraordinary condition that causes certain senses to leak' into one another.\"\\n\\n**Synonyms:**\\n• definition = meaning literally... an extraordinary condition that causes...",
  34: "Paragraph F offers two theories: either brain connections are cut as we age, or they remain but are hidden/repressed.\\n\\n**Highlighted Text:** \"...connections are pruned, so our senses become separated and the synesthetic mechanism is no longer intact. It's an idea that has been challenged... which suggests the mechanism is intact in adults but repressed.\"\\n\\n**Synonyms:**\\n• two different explanations = connections are pruned... challenged... suggests mechanism is intact but repressed",
  35: "Paragraph B explains that many hide their condition because they are afraid of being mocked.\\n\\n**Highlighted Text:** \"Others learn to keep it a secret for fear of people laughing at them.\"\\n\\n**Synonyms:**\\n• do not tell people = keep it a secret\\n• reason = fear of people laughing at them",
  36: "The passage implies Kandinsky had a highly positive/admiring view of synesthetes by comparing them to a beautiful, finely tuned musical instrument.\\n\\n**Highlighted Text:** \"...Wassily Kandinsky, who believed synesthetes were like good, much-played violins, which vibrate in all their parts and fibres.\"\\n\\n**Synonyms:**\\n• admired = believed they were like good, much-played violins",
  37: "The passage states that the old belief linking the condition to mental illness is no longer accepted as true.\\n\\n**Highlighted Text:** \"Early claims that the multi-sensory experiences of synesthesia were linked with the hallucinations of mental illness have long been disproved.\"\\n\\n**Synonyms:**\\n• no longer believed = long been disproved\\n• associated with = linked with",
  38: "The text explicitly states that women are much more likely to have the condition than men, contradicting the idea of \"equal numbers.\"\\n\\n**Highlighted Text:** \"Women are between two and eight times more likely than men to have the condition.\"\\n\\n**Synonyms:**\\n• Equal numbers (contradiction) = two and eight times more likely",
  39: "The text discusses how synesthetes perceive colours, sounds, and perform arithmetic (Paragraph H), but it never evaluates or compares their \"powers of logic\" against people with normal perception.",
  40: "The passage presents a scientific theory suggesting that every human is born with these linked senses.\\n\\n**Highlighted Text:** \"From this comes the notion that we may all have synesthesia at birth, when many parts of the brain are linked...\"\\n\\n**Synonyms:**\\n• possible = notion that we may all have\\n• born with = at birth"
};

let content = fs.readFileSync('src/data/test14ReadingData.ts', 'utf8');
const jsExplanations = content.match(/export const test14Explanations: Record<number, any> = (\{[\s\S]*?\});/);

if (jsExplanations) {
  const ex = JSON.parse(jsExplanations[1]);

  for (const key in ex) {
    if (fullExplanations[key]) {
      ex[key].explanation = fullExplanations[key];
    }
  }

  content = content.replace(jsExplanations[1], JSON.stringify(ex, null, 2));
  fs.writeFileSync('src/data/test14ReadingData.ts', content);
  console.log("Restored full explanations");
}
